name: skkaemok
description: A Skript addon focused on changing player nametags, skins, and more
author: kkaemok
website: https://github.com/kkaemok/Skkaemok
version: '${version}'
main: org.kkaemok.skkaemok.Skkaemok
api-version: '1.21'
depend: [ProtocolLib, Skript]
softdepend: [LuckPerms, TAB]
commands:
  skkaemok:
    description: Skkaemok management commands
    usage: /<command> <reload>
permissions:
  skkaemok.op:
    description: Allows Skkaemok management commands.
    default: op
